name: Publish Docker Image - Ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: crhubottom/EGCBOTV2
          ref: main  # or specify the branch or tag to pull from

      - name: Build and push combined Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.docker/Dockerfile
          push: false
          tags: |
            crhubottom/EGCBOTV2:latest
            crhubottom/EGCBOTV2:main
